name: "simple CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd ${{ secrets.PROJECT_FOLDER }}
            git pull
            docker stop notion
            docker build -t notion .
            docker run --name notion -d notion
